### ISSUE TITLE
Add scrolling to list of rulesets

### ISSUE THREAD

**Issue by swehba** [No3371/obsidian-regex-pipeline#1]
Love your plugin. I use it all the time. However, I now have a fairly long list of rulesets, and the ruleset selection window within Obsidian does not scroll. Would it be possible to add scrolling? Cheers.

**Comment by No3371** [comment]
Thanks, it feels really nice to hear from my users.

Talking about the feature request, don't you think scrolling is kinda wasting time? Let me try to do better then that.
![圖片](https://user-images.githubusercontent.com/1814971/122654068-6f18a200-d17b-11eb-89a2-e59c3d70bd9a.png)
