### ISSUE TITLE
Applying ruleset does not retain the current cursor position

### ISSUE THREAD

**Issue by ironfroggy** [No3371/obsidian-regex-pipeline#10]
It would be really helpful if, after applying a ruleset, the cursor position was retained to the location before the operation was performed.

**Comment by No3371** [comment]
This feature was already added but it can't be accurate, it only record the line number before applying a ruleset.

Let's say we have a 1000 lines note and the cursor is at line 500, we run a ruleset that removes or adds some lines both before and after line 500, and the final line count is 913.

There's no way the plugin will know which line is the previous line 500.

**Comment by ironfroggy** [comment]
I tried to take a crack at improving its ability to keep the cursor in place. I think I can at least keep it on the same line when the change doesn't remove that line, so it should work for any single-line replacements.

**Comment by No3371** [comment]
Yes, to completely solve this problem, the plugin must know how the line will be transformed and search it again after applying the ruleset.

This means, any replacement that works across more than 1 lines may break this functionality, I can not compromise reliability for a new feature, so this will not be implemented.
