### ISSUE TITLE
Extension of Rulesets

### ISSUE THREAD

**Issue by Pazukulele** [No3371/obsidian-regex-pipeline#13]
Rulesets are defined in .txt format, but without extension. For saving, please add the extension ".txt" because otherwise you have to rename it manually on MacOS to edit it.

**Comment by No3371** [comment]
As long as the filename is recorded in the index.txt, it'll work with or without extension.

Or are you talking about the examples?

**Comment by No3371** [comment]
For the ruleset creation UI, it's more straight forward than you might think.

Just name it `ruleset.txt`, the new file would be `ruleset.txt`.

**Comment by Pazukulele** [comment]
Thanks, now I see. Great plugin!
