### ISSUE TITLE
New line character in the replacement side

### ISSUE THREAD

**Issue by beniza** [No3371/obsidian-regex-pipeline#15]
Could you please provide a  sample that has inserts a new line (`\n`) character on the replacement side. For example if I want to split a timestamp 01:30 to

```
01
30
```
how do I do it?

I tried the following, but didn't work:
```regex
  "(\d{2}:\d{2})"->"$1\n$2"
  "(\d{2}:\d{2})"->"$1\r\n$2"
  "(\d{2}:\d{2})"->"$1`\n`$2"
```

**Comment by beniza** [comment]
Never mind... I found the workaround

I used <br> tag to insert a new line.

**Comment by No3371** [comment]
It's pretty plain:
"(\d{2}:\d{2})"->"$1
$2"

**Comment by beniza** [comment]
It's plain, but not really the regex way. So it might help you give some explicit information/documentation. Anyways, I'm very grateful for the plugin. So a big thanks to you!

**Comment by No3371** [comment]
Not trying to argue but I'd like to clarify this is included in the [readme](https://github.com/No3371/obsidian-regex-pipeline#multi-line-replacement-string).

And thanks for the kind words! By the way 1.3 was released just not long ago, get a update and enjoy😄

**Comment by howardpy** [comment]
Hi, a bit new here with regex, this is a great plugin.
Why is it not "(\d{2}):(\d{2})" ->"$1\n$2"? That may also help me understand why I can get Regex Find/Replace plugin to work but have no success with Regex Pipeline to delete [[ and ]] in linked file lists.

**Comment by No3371** [comment]
Your regex is not wrong at all. To be honest this is Regex Pipeline not doing enough to follow the convention.
To handle escaped character like `\n`, the plugin must be able to properly recognize `\` and `\\` (allow escaping slashes) , and for now I personally have no motivation to add it when it's already working for me.

**Comment by beniza** [comment]
Oh yeah! It was already there. That was my mistake. I somehow couldn't see
it because I was looking for `\n`s on the right side as well.
