### ISSUE TITLE
Replace doesn't work except for examples

### ISSUE THREAD

**Issue by howardpy** [No3371/obsidian-regex-pipeline#16]
It works like a charm for example regex, but I haven't got it to work with my own regexp, even though I tested it at regexp101.com, and another plugin Regex Search and Replace also works as expected.

Either of these doesn't work and always had 0 replacement:
"[[" gm -> "any" X
"\[\[" gm -> "any" x

below attempts didn't solve the issue either:
- copy the expression to an existing example ruleset
- add new ruleset from obsidian
- restart obsidian 

appreciate any idea, a good and useful plugin.
Mac OS
Obsidian 0.15.9, Blue Topaz theme

**Comment by No3371** [comment]
> "[[" gm -> "any" X
> "[[" gm -> "any" x
Please try again without a space before the `gm` flag. By the way, `gm` is applied by default, manually setting `gm` it's not needed.

**Comment by howardpy** [comment]
Thanks for that, space is indeed the devil! I'll get rid of the unnecessary space. thanks!
BTW, It does require using "\[\[" instead of just "[[" to work though, which is understandable as "[" or "]" has other meanings in regex.

**Comment by No3371** [comment]
> using "[[" instead of just "[["
I'm not sure if I follow, but if you are trying to match `[[`, you should use "\[\[".
