### ISSUE TITLE
List of rulesets does not respect modal width resulting in scrollbar

### ISSUE THREAD

**Issue by GeekPro101** [No3371/obsidian-regex-pipeline#19]
![image](https://user-images.githubusercontent.com/14115426/215191970-53f24f64-689d-4ad6-8973-3cbd94cea25e.png)

As seen here, the ruleset list does not wrap correctly, resulting in the scrollbar
This is due to a hardcoded width in styles: https://github.com/No3371/obsidian-regex-pipeline/blob/723bda7a8e3e73b9eabd5e10753cf2a64550d551/styles.css#L2

This should be set to 100% to ensure it takes up the whole available modal width without going beyond it

PR incoming

**Comment by No3371** [comment]
Interesting. IIRC it was not rendered like this (though there's some other issue), I guess it's broken by the style changes introduced in previous updates.

Merging, thanks!
