### ISSUE TITLE
wrong count

### ISSUE THREAD

**Issue by AlexWeng000** [No3371/obsidian-regex-pipeline#35]
no matter how many times the plugin actually replace in md，The plugin's notification always displays "Executed ruleset '……' which contains 1 regex replacements!" so that i donot know actual count.

**Comment by AlexWeng000** [comment]
another suggest. At present, it is not possible to see which text the plugin replaces. I hope to add a feature that highlights the text to be replaced before the replacement occurs.

**Comment by No3371** [comment]
> no matter how many times the plugin actually replace in md，The plugin's notification always displays "Executed ruleset '……' which contains 1 regex replacements!" so that i donot know actual count.

It's counting the rule executed.

> another suggest. At present, it is not possible to see which text the plugin replaces. I hope to add a feature that highlights the text to be replaced before the replacement occurs.

Not planned. It would be as much or more code than whole current code.
