### ISSUE TITLE
Stop scrolling to beginning after applying regex

### ISSUE THREAD

**Issue by hidara2000** [No3371/obsidian-regex-pipeline#5]
Thank you for a great plugin.
Is there any way to apply the regex without it scrolling back to the beginning of the text afterwards. 
I have to paste a lot of data and then apply rules to this data. After every regex I have to scroll down the page again, back to where I was working. 
Ideally I could apply a regex and my cursor would remain where it was. 
Even better, would be the ability to highlight a portion of text and select regex rule to apply from **right click menu**

Thanks again

**Comment by No3371** [comment]
- [x] Scroll back near where it was
- [ ] Context menu

**Comment by No3371** [comment]
Hey, v1.1.0 is released.

Now rulesets are available through right click menu.

As for `highlight a portion of text`, when something is selected, the plugin already only apply ruleset on the selection (if any), this has been implemented very long ago; it should already works.

**Comment by hidara2000** [comment]
Thank you
