### ISSUE TITLE
Cannot apply ruleset to Kanban view

### ISSUE THREAD

**Issue by teake** [No3371/obsidian-regex-pipeline#8]
If I want to apply a ruleset to a kanban board made with the [Kanban plugin](https://github.com/mgmeyers/obsidian-kanban/), I get an error saying "No active Markdown file!". I have to go into the Markdown view, apply the ruleset, and then switch to the kanban via again.

Would it be possible to directly apply rulesets to kanban boards?

**Comment by No3371** [comment]
The active file is an internal field of Obsidian. According to what you describe, it seems that the Kanban board is not setting the value or the field is set otherwise during your operation.
